/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface LoginBody {
  body: {
    email: string;
    password: string;
  };
}

export interface RefreshTokenBody {
  body: {
    refreshToken: string;
  };
}

export interface SignUpBody {
  body: {
    email: string;
    firstName: string;
    googleId?: string;
    lastName?: string;
    password: string;
    phone?: string;
  };
}
