/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface Login {
  body: {
    email: string;
    password: string;
  };
}

export interface Register {
  body?: {
    email: string;
    name: string;
    password: string;
  };
}
